[2025-10-06T13:03:01.137+0000] {processor.py:161} INFO - Started process (PID=88) to work on /opt/airflow/dags/airflow.py
[2025-10-06T13:03:01.138+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/airflow.py for tasks to queue
[2025-10-06T13:03:01.141+0000] {logging_mixin.py:188} INFO - [2025-10-06T13:03:01.141+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/airflow.py
[2025-10-06T13:03:01.152+0000] {logging_mixin.py:188} INFO - [2025-10-06T13:03:01.152+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/airflow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/airflow.py", line 4, in <module>
    from airflow.providers.standard.operators.python import PythonOperator
ModuleNotFoundError: No module named 'airflow.providers.standard'
[2025-10-06T13:03:01.153+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/airflow.py
[2025-10-06T13:03:01.179+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/airflow.py took 0.048 seconds
[2025-10-06T13:03:31.855+0000] {processor.py:161} INFO - Started process (PID=95) to work on /opt/airflow/dags/airflow.py
[2025-10-06T13:03:31.857+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/airflow.py for tasks to queue
[2025-10-06T13:03:31.872+0000] {logging_mixin.py:188} INFO - [2025-10-06T13:03:31.869+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/airflow.py
[2025-10-06T13:03:31.926+0000] {logging_mixin.py:188} INFO - [2025-10-06T13:03:31.920+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/airflow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/airflow.py", line 4, in <module>
    from airflow.providers.standard.operators.python import PythonOperator
ModuleNotFoundError: No module named 'airflow.providers.standard'
[2025-10-06T13:03:31.932+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/airflow.py
[2025-10-06T13:03:32.028+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/airflow.py took 0.197 seconds
[2025-10-06T13:04:02.389+0000] {processor.py:161} INFO - Started process (PID=102) to work on /opt/airflow/dags/airflow.py
[2025-10-06T13:04:02.390+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/airflow.py for tasks to queue
[2025-10-06T13:04:02.393+0000] {logging_mixin.py:188} INFO - [2025-10-06T13:04:02.393+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/airflow.py
[2025-10-06T13:04:02.396+0000] {logging_mixin.py:188} INFO - [2025-10-06T13:04:02.396+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/airflow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/airflow.py", line 4, in <module>
    from airflow.providers.standard.operators.python import PythonOperator
ModuleNotFoundError: No module named 'airflow.providers.standard'
[2025-10-06T13:04:02.396+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/airflow.py
[2025-10-06T13:04:02.416+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/airflow.py took 0.084 seconds
[2025-10-06T13:04:32.720+0000] {processor.py:161} INFO - Started process (PID=109) to work on /opt/airflow/dags/airflow.py
[2025-10-06T13:04:32.721+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/airflow.py for tasks to queue
[2025-10-06T13:04:32.723+0000] {logging_mixin.py:188} INFO - [2025-10-06T13:04:32.723+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/airflow.py
[2025-10-06T13:04:32.726+0000] {logging_mixin.py:188} INFO - [2025-10-06T13:04:32.726+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/airflow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/airflow.py", line 4, in <module>
    from airflow.providers.standard.operators.python import PythonOperator
ModuleNotFoundError: No module named 'airflow.providers.standard'
[2025-10-06T13:04:32.726+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/airflow.py
[2025-10-06T13:04:32.745+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/airflow.py took 0.032 seconds
[2025-10-06T13:05:03.201+0000] {processor.py:161} INFO - Started process (PID=116) to work on /opt/airflow/dags/airflow.py
[2025-10-06T13:05:03.203+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/airflow.py for tasks to queue
[2025-10-06T13:05:03.212+0000] {logging_mixin.py:188} INFO - [2025-10-06T13:05:03.211+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/airflow.py
[2025-10-06T13:05:03.222+0000] {logging_mixin.py:188} INFO - [2025-10-06T13:05:03.220+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/airflow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/airflow.py", line 4, in <module>
    from airflow.providers.standard.operators.python import PythonOperator
ModuleNotFoundError: No module named 'airflow.providers.standard'
[2025-10-06T13:05:03.222+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/airflow.py
[2025-10-06T13:05:03.311+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/airflow.py took 0.133 seconds
[2025-10-06T13:05:34.378+0000] {processor.py:161} INFO - Started process (PID=123) to work on /opt/airflow/dags/airflow.py
[2025-10-06T13:05:34.391+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/airflow.py for tasks to queue
[2025-10-06T13:05:34.437+0000] {logging_mixin.py:188} INFO - [2025-10-06T13:05:34.423+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/airflow.py
[2025-10-06T13:05:34.591+0000] {logging_mixin.py:188} INFO - [2025-10-06T13:05:34.579+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/airflow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/airflow.py", line 4, in <module>
    from airflow.providers.standard.operators.python import PythonOperator
ModuleNotFoundError: No module named 'airflow.providers.standard'
[2025-10-06T13:05:34.593+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/airflow.py
[2025-10-06T13:05:35.264+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/airflow.py took 1.107 seconds
[2025-10-06T13:06:05.676+0000] {processor.py:161} INFO - Started process (PID=130) to work on /opt/airflow/dags/airflow.py
[2025-10-06T13:06:05.677+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/airflow.py for tasks to queue
[2025-10-06T13:06:05.685+0000] {logging_mixin.py:188} INFO - [2025-10-06T13:06:05.685+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/airflow.py
[2025-10-06T13:06:05.692+0000] {logging_mixin.py:188} INFO - [2025-10-06T13:06:05.691+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/airflow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/airflow.py", line 4, in <module>
    from airflow.providers.standard.operators.python import PythonOperator
ModuleNotFoundError: No module named 'airflow.providers.standard'
[2025-10-06T13:06:05.692+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/airflow.py
[2025-10-06T13:06:05.721+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/airflow.py took 0.059 seconds
[2025-10-06T13:06:36.181+0000] {processor.py:161} INFO - Started process (PID=137) to work on /opt/airflow/dags/airflow.py
[2025-10-06T13:06:36.184+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/airflow.py for tasks to queue
[2025-10-06T13:06:36.194+0000] {logging_mixin.py:188} INFO - [2025-10-06T13:06:36.190+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/airflow.py
[2025-10-06T13:06:36.205+0000] {logging_mixin.py:188} INFO - [2025-10-06T13:06:36.203+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/airflow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/airflow.py", line 4, in <module>
    from airflow.providers.standard.operators.python import PythonOperator
ModuleNotFoundError: No module named 'airflow.providers.standard'
[2025-10-06T13:06:36.206+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/airflow.py
[2025-10-06T13:06:36.305+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/airflow.py took 0.153 seconds
[2025-10-06T13:07:06.471+0000] {processor.py:161} INFO - Started process (PID=144) to work on /opt/airflow/dags/airflow.py
[2025-10-06T13:07:06.473+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/airflow.py for tasks to queue
[2025-10-06T13:07:06.475+0000] {logging_mixin.py:188} INFO - [2025-10-06T13:07:06.474+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/airflow.py
[2025-10-06T13:07:06.484+0000] {logging_mixin.py:188} INFO - [2025-10-06T13:07:06.483+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/airflow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/airflow.py", line 4, in <module>
    from airflow.providers.standard.operators.python import PythonOperator
ModuleNotFoundError: No module named 'airflow.providers.standard'
[2025-10-06T13:07:06.485+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/airflow.py
[2025-10-06T13:07:06.504+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/airflow.py took 0.047 seconds
[2025-10-06T13:07:36.861+0000] {processor.py:161} INFO - Started process (PID=151) to work on /opt/airflow/dags/airflow.py
[2025-10-06T13:07:36.862+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/airflow.py for tasks to queue
[2025-10-06T13:07:36.865+0000] {logging_mixin.py:188} INFO - [2025-10-06T13:07:36.865+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/airflow.py
[2025-10-06T13:07:36.873+0000] {logging_mixin.py:188} INFO - [2025-10-06T13:07:36.872+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/airflow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/airflow.py", line 4, in <module>
    from airflow.providers.standard.operators.python import PythonOperator
ModuleNotFoundError: No module named 'airflow.providers.standard'
[2025-10-06T13:07:36.873+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/airflow.py
[2025-10-06T13:07:36.893+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/airflow.py took 0.047 seconds
