[2025-10-07T01:15:01.410+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-10-07T01:15:01.423+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Airflow_Lab2.load_model_task manual__2025-10-07T01:14:35.811608+00:00 [queued]>
[2025-10-07T01:15:01.433+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Airflow_Lab2.load_model_task manual__2025-10-07T01:14:35.811608+00:00 [queued]>
[2025-10-07T01:15:01.434+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2025-10-07T01:15:01.441+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): load_model_task> on 2025-10-07 01:14:35.811608+00:00
[2025-10-07T01:15:01.464+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=182) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-10-07T01:15:01.466+0000] {standard_task_runner.py:63} INFO - Started process 191 to run task
[2025-10-07T01:15:01.466+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'Airflow_Lab2', 'load_model_task', 'manual__2025-10-07T01:14:35.811608+00:00', '--job-id', '9', '--raw', '--subdir', 'DAGS_FOLDER/main.py', '--cfg-path', '/tmp/tmpl58jv66m']
[2025-10-07T01:15:01.470+0000] {standard_task_runner.py:91} INFO - Job 9: Subtask load_model_task
[2025-10-07T01:15:01.503+0000] {task_command.py:426} INFO - Running <TaskInstance: Airflow_Lab2.load_model_task manual__2025-10-07T01:14:35.811608+00:00 [running]> on host a2f5a30149ba
[2025-10-07T01:15:01.589+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='Airflow_Lab2' AIRFLOW_CTX_TASK_ID='load_model_task' AIRFLOW_CTX_EXECUTION_DATE='2025-10-07T01:14:35.811608+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-10-07T01:14:35.811608+00:00'
[2025-10-07T01:15:01.589+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-10-07T01:15:01.787+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/sklearn/ensemble/_base.py:168: UserWarning: Loky-backed parallel loops cannot be called in a multiprocessing, setting n_jobs=1
  n_jobs = min(effective_n_jobs(n_jobs), n_estimators)

[2025-10-07T01:15:01.849+0000] {logging_mixin.py:188} INFO - RandomForest accuracy on test data: 0.9903
[2025-10-07T01:15:01.850+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/sklearn/ensemble/_base.py:168: UserWarning: Loky-backed parallel loops cannot be called in a multiprocessing, setting n_jobs=1
  n_jobs = min(effective_n_jobs(n_jobs), n_estimators)

[2025-10-07T01:15:01.859+0000] {python.py:237} INFO - Done. Returned value was: 0
[2025-10-07T01:15:01.859+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-10-07T01:15:01.897+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=Airflow_Lab2, task_id=load_model_task, run_id=manual__2025-10-07T01:14:35.811608+00:00, execution_date=20251007T011435, start_date=20251007T011501, end_date=20251007T011501
[2025-10-07T01:15:01.944+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2025-10-07T01:15:01.965+0000] {taskinstance.py:3503} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-10-07T01:15:01.966+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
