[2025-10-06T13:14:26.717+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-10-06T13:14:26.757+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Airflow_Lab1.load_model_task scheduled__2025-10-05T00:00:00+00:00 [queued]>
[2025-10-06T13:14:26.771+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Airflow_Lab1.load_model_task scheduled__2025-10-05T00:00:00+00:00 [queued]>
[2025-10-06T13:14:26.771+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2025-10-06T13:14:26.782+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): load_model_task> on 2025-10-05 00:00:00+00:00
[2025-10-06T13:14:26.813+0000] {standard_task_runner.py:63} INFO - Started process 254 to run task
[2025-10-06T13:14:26.820+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'Airflow_Lab1', 'load_model_task', 'scheduled__2025-10-05T00:00:00+00:00', '--job-id', '13', '--raw', '--subdir', 'DAGS_FOLDER/lab1_dag.py', '--cfg-path', '/tmp/tmphbm5jvby']
[2025-10-06T13:14:26.827+0000] {standard_task_runner.py:91} INFO - Job 13: Subtask load_model_task
[2025-10-06T13:14:26.875+0000] {task_command.py:426} INFO - Running <TaskInstance: Airflow_Lab1.load_model_task scheduled__2025-10-05T00:00:00+00:00 [running]> on host c8d8a3d8ee97
[2025-10-06T13:14:26.932+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='your_name' AIRFLOW_CTX_DAG_ID='Airflow_Lab1' AIRFLOW_CTX_TASK_ID='load_model_task' AIRFLOW_CTX_EXECUTION_DATE='2025-10-05T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-10-05T00:00:00+00:00'
[2025-10-06T13:14:26.933+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-10-06T13:14:26.962+0000] {logging_mixin.py:188} INFO - Optimal no. of clusters: 8
[2025-10-06T13:14:26.980+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.10/site-packages/sklearn/utils/validation.py:2742: UserWarning: X has feature names, but KMeans was fitted without feature names
  warnings.warn(

[2025-10-06T13:14:27.038+0000] {python.py:237} INFO - Done. Returned value was: 5
[2025-10-06T13:14:27.057+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-10-06T13:14:27.093+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=Airflow_Lab1, task_id=load_model_task, run_id=scheduled__2025-10-05T00:00:00+00:00, execution_date=20251005T000000, start_date=20251006T131426, end_date=20251006T131427
[2025-10-06T13:14:27.128+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2025-10-06T13:14:27.142+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-10-06T13:14:27.146+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
